In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])

In [5]:
print(a)

[1 2 3 4]


In [6]:
import time

In [7]:
a=np.random.rand(1000000)

In [8]:
b=np.random.rand(1000000)

In [15]:
a=np.random.rand(1000000)
b=np.random.rand(1000000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()
t=toc-tic
print(t)
c=0
tic=time.time()
for i in range(1000000):
    c=c+a[i]*b[i]
toc=time.time()
t=toc-tic
print(t)

0.00107288360596
0.713734865189


In [33]:
A=np.array([[56,0,4.4,68],
          [1.2,104,52,8],
          [1.8,135,99,0.9]])

In [34]:
A

array([[  56. ,    0. ,    4.4,   68. ],
       [   1.2,  104. ,   52. ,    8. ],
       [   1.8,  135. ,   99. ,    0.9]])

In [35]:
 cal=A.sum(axis=0)

In [36]:
cal

array([  59. ,  239. ,  155.4,   76.9])

In [43]:
p=100*A/cal.reshape(1,4)

In [44]:
p

array([[ 94.91525424,   0.        ,   2.83140283,  88.42652796],
       [  2.03389831,  43.51464435,  33.46203346,  10.40312094],
       [  3.05084746,  56.48535565,  63.70656371,   1.17035111]])

In [53]:
a=np.random.randn(5)

In [54]:
a

array([-0.27890844, -0.04083035,  0.25250836,  0.19115359,  1.68580968])

In [55]:
print(a.shape)
print(a.T.shape)

(5,)
(5,)


In [56]:
a=np.random.randn(5,1)
print(a.shape)
print(a.T.shape)

(5, 1)
(1, 5)


In [58]:
a=np.random.randn(4,3)
b=np.random.randn(3,2)
c=a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [59]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
c.shape

(12288, 45)

In [67]:
a = np.random.randn(3, 4) 
b = np.random.randn(4, 1) 
c=np.numpy(1,3)
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

AttributeError: 'module' object has no attribute 'numpy'

In [68]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [69]:
c

array([[ 1.03035299, -0.76791762, -0.83173017],
       [-0.00212671,  0.07751261, -0.06765747],
       [-0.26703655,  0.26781535, -0.55575756]])

In [70]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)

In [71]:
a

array([[ 0.26728105,  1.87207002,  0.09129593],
       [ 0.50139555, -0.15519794, -0.12179264],
       [ 0.67883375,  0.76171415,  0.19485147]])

In [72]:
b

array([[-0.87806729],
       [ 0.33531512],
       [ 0.01841724]])

In [83]:
img = np.random.randn(2,2,2)

In [84]:
img

array([[[-1.3436438 ,  2.28664904],
        [ 0.72144268, -1.40325275]],

       [[ 0.96062277, -0.29252487],
        [ 0.09823684,  1.32246978]]])

In [85]:
img.reshape(2*2,2)

array([[-1.3436438 ,  2.28664904],
       [ 0.72144268, -1.40325275],
       [ 0.96062277, -0.29252487],
       [ 0.09823684,  1.32246978]])

In [86]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [88]:
c.shape

(2, 3)